standalone_tags:
  [
    {id: 1, size: 0.172},
    {id: 2, size: 0.172},
    {id: 3, size: 0.172},
    {id: 4, size: 0.172},
    {id: 5, size: 0.172},
    {id: 6, size: 0.172},
    {id: 7, size: 0.172},
    {id: 8, size: 0.172},
    {id: 9, size: 0.172},
    {id: 10, size: 0.172},
    {id: 11, size: 0.172},
    {id: 12, size: 0.172},
  ]